version = "3.10.4"
runner.dialect = scala3

maxColumn = 120

align.preset = some
align.tokens = [
  {code = "=>", owner = "Case"},
  {code = "%", owner = "Term.ApplyInfix"},
  {code = "%%", owner = "Term.ApplyInfix"}
]
align.openParenCallSite = false
align.openParenDefnSite = false

newlines.source = keep
newlines.topLevelStatementBlankLines = [
  { blanks { before = 1, after = 1, beforeEndMarker = 0 } }
]
newlines.beforeMultiline = keep
newlines.alwaysBeforeMultilineDef = false

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  Imports
]

rewrite.imports.sort = scalastyle
rewrite.imports.groups = [
  ["java\\..*", "javax\\..*", "scala\\..*"]
]

spaces.inImportCurlyBraces = true

rewrite.scala3.convertToNewSyntax = true
