addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"    % "0.12.0")
addSbtPlugin("com.github.sbt" % "sbt-dynver"       % "5.0.1")
addSbtPlugin("org.scalameta"  % "sbt-native-image" % "0.3.2")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"     % "2.5.2")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"     % "0.13.0")
